### PR TITLE
Connection get stream and isReady when its writable

### PR DESCRIPTION
**Pull request by choval**
Hi, I've changed the connection a bit.

I changed the stream from private to protected, since the class itself is not final and I needed to add the following methods:

- getStream
- isReady

### CODE REVIEW

**Comment by mbonneau** [comment]
Hi @choval 

If you could explain the use case of this, that would be helpful.

I have also looked for the `isReady` method on the `DuplexStreamInterface` and I don't see it. Am I missing something?

Also, if you need a reference to that stream, you can call `$response->getBody()` in the callable that handles the initial websocket connection.

**Comment by choval** [comment]
On connection, the stream is not immediatly available for writing, this can be checked by calling `stream->isWritable` (which is what `isReady` does).

I tried to access the stream and call isWritable directly, but the var is private and has no getter. If i extend it, it's private.

**Comment by mbonneau** [comment]
You can check `$response->getBody()->isWritable()` to check if that stream is writable:

```php
$ws = new WebSocketMiddleware(['/ws'], function (WebSocketConnection $conn,
                                                 ServerRequestInterface $request,
                                                 ResponseInterface $response) {

    echo "New Connection - writable? " . json_encode($response->getBody()->isWritable()) . "\n";
    // ---- Other code to handle websocket stuff
```

**Comment by choval** [comment]
It's not the same, that is the 101 handshake response.

The WebSocketConnection stream is the one used for sending messages after the connection is made and that one is not immediatly available.

**Comment by choval** [comment]
Looking through the example, you add a 0 timer. I need that ready state, but I cannot get it from the connection itself and I cannot access the stream property if I extend the class.

```php
    // do not send on the connection before the react http server has a chance to start listening
    // on the streams
    $loop->addTimer(0, function () use ($conn, $user, $broadcast) { 
        $broadcast->write('user ' . $user . ' connected');
        $conn->send('Welcome. You are user ' . $user);
    });
```

**Comment by choval** [comment]
Dropping the pull request

**Pull request closed without merging**
